import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"
import Header from "@/src/components/layout/home/Header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NameApp",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex flex-col items-center justify-center p-2">
        <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col justify-center items-center lg:w-3/4 p-2`}>
          <Header/>
          {children}
        </body>
    </html>
  );
}
